### ISSUE TITLE
Error: Unable to process file command 'env' successfully.

### ISSUE THREAD

**Issue by stavares843** [sobolevn/misspell-fixer-action#13]
Hello! 👋 

using the following

````
name: Automatically fix typos
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v4.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
````

returns the following error

```
Error: Unable to process file command 'env' successfully.
Error: Invalid format '+++ ./2019/index.html.68	2023-02-06 17:41:04.556125250 +0000'
``` 

I have been using this CI a lot and was working fine, but today returns error. I have tried a couple things but didn't work.

Full log [here](https://github.com/stavares843/monadical.com/actions/runs/4106357105/jobs/7084477726#step:4:109).

I also tried without the

````
env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
````

but still returns error
